"""
Extract JSON Schema from SETU OpenAPI specification.

This module converts the OpenAPI 3.1.0 YAML specification to a JSON Schema
compatible with the jsonschema library for local validation.
"""

import json
from pathlib import Path
from typing import Any

import yaml


class SETUSchemaExtractor:
    """Extract and convert SETU OpenAPI schema to JSON Schema format."""

    def __init__(self, openapi_file: Path):
        """
        Initialize extractor with OpenAPI YAML file.

        Args:
            openapi_file: Path to gelijkwaardige-beloning-api.yaml
        """
        self.openapi_file = openapi_file
        with open(openapi_file, encoding='utf-8') as f:
            self.openapi_spec = yaml.safe_load(f)

    def extract_version(self) -> str:
        """Extract schema version from OpenAPI info."""
        return self.openapi_spec['info']['version']

    def extract_json_schema(self) -> dict[str, Any]:
        """
        Extract JSON Schema from OpenAPI specification.

        Returns:
            Complete JSON Schema for InquiryPayEquity with all $defs
        """
        schemas = self.openapi_spec['components']['schemas']
        inquiry_schema = schemas['InquiryPayEquity']

        # Convert all $ref paths from #/components/schemas/ to #/$defs/
        def fix_refs(obj):
            """Recursively fix $ref paths"""
            if isinstance(obj, dict):
                if '$ref' in obj:
                    obj['$ref'] = obj['$ref'].replace('#/components/schemas/', '#/$defs/')
                for value in obj.values():
                    fix_refs(value)
            elif isinstance(obj, list):
                for item in obj:
                    fix_refs(item)

        # Fix references in all schemas
        for schema in schemas.values():
            fix_refs(schema)

        # Build complete schema with all definitions
        complete_schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": inquiry_schema.get('$id', 'https://ontology.setu.nl/inquiry-pay-equity/InquiryPayEquity'),
            "title": inquiry_schema.get('title', 'SETU Inquiry Pay Equity v2.0'),
            "description": inquiry_schema.get('description', 'Generated by Semantic Treehouse'),
            "type": "object",
            "required": inquiry_schema.get('required', []),
            "additionalProperties": inquiry_schema.get('additionalProperties', False),
            "properties": inquiry_schema.get('properties', {}),
            "$defs": schemas  # All component schemas as definitions
        }

        return complete_schema

    def save_schema(self, output_file: Path) -> None:
        """
        Extract and save JSON Schema to file.

        Args:
            output_file: Where to save the JSON Schema
        """
        schema = self.extract_json_schema()
        version = self.extract_version()

        # Add metadata
        schema['_metadata'] = {
            'version': version,
            'extracted_from': str(self.openapi_file),
            'extraction_date': '2026-03-05',
            'source': self.openapi_spec['info'].get('title', 'SETU API for Inquiry Pay Equity')
        }

        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(schema, f, indent=2, ensure_ascii=False)

        print(f"✅ Extracted JSON Schema v{version}")
        print(f"   Schemas: {len(schema['$defs'])} definitions")
        print(f"   Required: {len(schema['required'])} root fields")
        print(f"   Saved to: {output_file}")

    def analyze_schema(self) -> dict[str, Any]:
        """
        Analyze schema to identify key structures and constraints.

        Returns:
            Analysis report with enums, required fields, format constraints
        """
        schemas = self.openapi_spec['components']['schemas']

        analysis = {
            'total_schemas': len(schemas),
            'enums': {},
            'required_fields': {},
            'format_constraints': {},
            'complex_structures': []
        }

        for schema_name, schema_def in schemas.items():
            # Find enums
            if 'enum' in schema_def:
                analysis['enums'][schema_name] = schema_def['enum']

            # Find required fields
            if 'required' in schema_def:
                analysis['required_fields'][schema_name] = schema_def['required']

            # Find format constraints
            if 'format' in schema_def:
                analysis['format_constraints'][schema_name] = schema_def['format']

            # Find properties with formats
            if 'properties' in schema_def:
                for prop_name, prop_def in schema_def['properties'].items():
                    if 'format' in prop_def:
                        key = f"{schema_name}.{prop_name}"
                        analysis['format_constraints'][key] = prop_def['format']

        return analysis


def main():
    """Extract SETU schema from OpenAPI YAML."""
    # Paths
    openapi_file = Path("data/setu_input/gelijkwaardige-beloning-api.yaml")
    output_file = Path("src/cao_engine/compliance/schemas/setu_v2.0.0-draft.3.json")

    # Extract
    extractor = SETUSchemaExtractor(openapi_file)
    extractor.save_schema(output_file)

    # Analyze
    print("\n📊 Schema Analysis:")
    analysis = extractor.analyze_schema()

    print(f"\n🔢 Total Schemas: {analysis['total_schemas']}")

    print(f"\n📋 Enums ({len(analysis['enums'])}):")
    for name, values in list(analysis['enums'].items())[:5]:
        print(f"   • {name}: {values}")
    if len(analysis['enums']) > 5:
        print(f"   ... and {len(analysis['enums']) - 5} more")

    print(f"\n✅ Required Fields ({len(analysis['required_fields'])}):")
    for name, fields in list(analysis['required_fields'].items())[:5]:
        print(f"   • {name}: {fields}")
    if len(analysis['required_fields']) > 5:
        print(f"   ... and {len(analysis['required_fields']) - 5} more")

    print(f"\n📝 Format Constraints ({len(analysis['format_constraints'])}):")
    for name, format_type in list(analysis['format_constraints'].items())[:10]:
        print(f"   • {name}: {format_type}")
    if len(analysis['format_constraints']) > 10:
        print(f"   ... and {len(analysis['format_constraints']) - 10} more")


if __name__ == "__main__":
    main()
